### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by VictorCoder123** [webgme/premonition#1]
- [x] Add Gulp task runner with nodemon.
- [x] Understand and write test for plugin.
- [x] Rename icon svg and update documentation

**Comment by lattmann** [comment]
With gulp we usually use gulp watch and not nodemon, but nodemon would work too.

https://github.com/webgme/webgme/blob/master/gulpfile.js#L51-L54

**Comment by VictorCoder123** [comment]
Good advice, I think nodemon is not necessary here as we don't need to restart webgme server after PipelinePlugin is changed. Thanks Zsolt
